### ISSUE TITLE
Franglais and frenish

### ISSUE THREAD

**Issue by nopid** [duprepNicolas/ter-celeste#1]
https://github.com/duprepNicolas/ter-celeste/blob/5f894e57bf71f896160c78fddf8b1d6581e4d6d3/Celeste-GBA/data.json#L15

All the other keys are in english.

**Comment by Falcommander** [comment]
Oopsie. I'm gonna fix that issue and I'll repeat 10 times "Don't write franglais/frenish" for the next 4 weeks.
